* Agris Robotic Simulator
** Description


-----

* YAML Configuration
** sim.yaml
** robot.yaml
** obstacles.yaml



---------

* Collision Detection
** Oriented bounding box vs Circles
 * The Robot is modeled as a a rectangle with sizing declared in the robot.yaml file. The obstacles are modeled as circles defined with radius and location declared in obstacles.yaml file.
   
 * Since the robots are modeled as squares with a heading it makes its much tougher than something like AABB or axis aligned bounding boxes.
   
 * The first step is to take the vector drawn from the (x,y) from the robot pose to the obstacles in the global reference space and transform it to the local reference frame of the robot.

 * After getting the transformed vector we can then compare the radius of the obstacle being checked to the edge of the robot at the given direction.

 * If a collision is detected, the simulator does not worry about collision reactions. It just prevents the new update from being stored keeping the robot at its current location.






* Kinematics
 * The kinematics are based on a simple differential drive system. The equations used are shown below.





* Rendering
 * Graphics are rendered using the c++ library SFML.


* Data Layer
** Debug
 * Left and right line distance
 * Line difference
 * PID results
 * RANSAC Lines
 * Left and Right PWM values
 * Yaw rate in degrees per second (Z)
   
* Sensors feedback
** Lidar
 * Lidar data is stored in radians with CCW positive like traditional math.
 * However hardware lidar expects CW positive for inputs so lidarc1sim.cpp converts the data by converting radians to degrees and subtracting by 360 to correct for this. 
** IMU
 * Might want to add gaussian noise to IMU simulation at some point.

------

* Transaction layer.
 * Had Claude setup a simple Arduino compatibility file to allow Arduino functions to work correctly.
 * sketch.cpp is the hardware code with minimum changes.
 * Robot grabs the lidar data and pushes it to sketch.cpp
 * sketch.cpp returns the PWM values and the kinematics are calculated.

-----

* Learning Docker
** Notes
 * I used this to play around with Docker containers and remote building.
 * The build environment is on an Ubuntu 22.04 VM running docker.
 * SFML was a pain to setup due to bugs in the most recent versions and issues with cross  compilations for windows.
 * I want to make it where the container doesnt output all the messsy cmake generated files but rather just the .exe
 * All files are statically linked so the only files needed are the font file and config files.
** Docker Setup
 * Ubuntu base image.
 * Gets tool chains required.
 * Clone SFML and YAML-cpp.
 * Builds both dependencies.
 * Setups directories for the project

------
*  To Do List
** TODO Make a build script that runs rsync and builds the project
** TODO Make class diagram
** TODO Clean up logger and maybe add more data to the display and logger?
** TODO Maybe make the switch from manual mode to auto mode zero out data layer and reset state.
** TODO Figure out a better setup for managing simulation time through the simulator. I think it might be messing up the PID and controls.


 docker run -it -v "$(pwd)":/project agrissim:latest